### ISSUE TITLE
Admin | Dashboard | Github Issue column header shouldn't be wrapped

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-feedback#70]
# Description
The "Github Issue" label is wrapping on the Admin Feedback page.  It should not wrap.

**Confirmed Environment(s)**
- [ ] Dev
- [x] Demo
- [ ] UAT
- [x] Prod

**Type of Bug**
- [ ] Functional
- [x] Design
- [ ] Security
- [ ] Tech Improvement

**Severity Level**
- [ ]    5 - Data loss, data corruption or system unavailable
- [ ]    4 - Important functionality is unavailable with no workaround
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround
- [x]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround

# Reproductive Steps
1. Login to the Caseflow Admin Feedback page.
1. In the table, the "Github Issue" column header is wrapping.

# Screenshot 
**_View - Admin Feedback page - Incorrect Wrapping_**
![image](https://cloud.githubusercontent.com/assets/23063044/22360353/d4442100-e41c-11e6-869f-017c991e44b6.png)

**_View - Admin Feedback page - Correct_**
![image](https://cloud.githubusercontent.com/assets/23063044/22360387/311240f6-e41d-11e6-9f36-0a6ab08ca186.png)

# Related Stories

**Comment by nikitarockz** [comment]
Suggestions:

As a product support team member, I want the View Feedback button to open the Feedback Details modal so I can easily read and interact with the feedback details.

Acceptance Criteria
1. Verify that that after clicking on the **_View Feedback_** link, the Feedback Details modal is displayed with the selected Feedback item details.
1. Verify that after clicking on the **_View Feedback_** link, the Admin Home page is grayed out the background.

Mockup Headers:  Use the following headers.
**_View - Admin Home page - View Feedback Link_**
**_View - Feedback Details Modal displayed active_**

**Comment by shanear** [comment]
@KHarshawat says that we can change the text to "Issue #" and that should fix this issue

**Comment by ghost** [comment]
<img width="164" alt="screen shot 2017-01-31 at 16 05 15" src="https://cloud.githubusercontent.com/assets/18075411/22484359/125a31cc-e7cf-11e6-82de-42ba85a13f72.png">
Still shows up as 2 lines and not 1.
<img width="164" alt="screen shot 2017-01-31 at 16 06 53" src="https://cloud.githubusercontent.com/assets/18075411/22484452/7d4b6b68-e7cf-11e6-858f-f5487b562aac.png">
<img width="86" alt="screen shot 2017-01-31 at 16 07 11" src="https://cloud.githubusercontent.com/assets/18075411/22484453/7d526d78-e7cf-11e6-92f4-cf1892f82241.png">

**Comment by nemodjuric** [comment]
@shanear @KHarshawat-gov Text change did not do it. We can enforce it through css, but we might have to consider fixing the layout issue first.

**Comment by KHarshawat-gov** [comment]
This is weird because that table is supposed to adjust the column width automatically I believe. I would focus on fixing the layout issue. Also consider just removing the `#` for now.

**Comment by ghost** [comment]
Removing `#` did it...
<img width="1071" alt="screen shot 2017-02-01 at 1 36 50 pm" src="https://cloud.githubusercontent.com/assets/18075411/22520776/aad7e43a-e883-11e6-9487-2dbc71d5dbf5.png">
tested `demo` and `uat`
